spring:
  profiles: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
      url: jdbc:mysql://localhost:3306/examen-flexibility?zeroDateTimeBehavior=convertToNull
      username: root
      password: root

server:
  port: 8080
  servlet:
    context-path: '/payments'

---
spring:
  profiles: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop
server:
  port: 0
logging:
  level:
    myapps: DEBUG